In [2]:
## Import necessary libraries 

import os 
import numpy as np 
import pandas as pd 
import keras
import datetime as dt
import matplotlib.pyplot as plt 
from sklearn.preprocessing import MinMaxScaler
from pandas_datareader import data

In [3]:
df = pd.read_csv("WFC_FSI_added.csv")
df.head()

,Date,Credit,Equity valuation,Safe assets,Funding,Volatility,United States,FSI,Open,High,Low,Close,Adj Close,Volume,2 days,3 days,5 days (1 week)
0,5/24/2010,0.613,0.304,0.224,1.092,2.001,1.699,4.234,29.570000,29.75,28.530001,28.709999,21.510351,64867000,0.000000,0.000000,0.0
1,5/25/2010,0.719,0.398,0.251,1.251,2.138,1.784,4.757,27.709999,28.91,27.440001,28.900000,21.652718,55196200,0.000000,0.000000,0.0
2,5/26/2010,0.686,0.348,0.244,1.086,1.891,1.666,4.255,29.230000,29.34,27.700001,28.040001,21.008373,62366800,-0.501978,0.000000,0.0
3,5/27/2010,0.618,0.211,0.175,0.948,1.483,1.292,3.435,28.709999,29.48,28.500000,29.410000,22.034821,48871900,0.382103,0.524470,0.0
4,5/28/2010,0.623,0.217,0.190,0.960,1.447,1.418,3.437,29.469999,29.50,28.540001,28.690001,21.495375,40885500,0.487002,-0.157343,0.0